default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hello_development

test:
  <<: *default
  database: hello_test

production:
  <<: *default
  database: hello_production
  username: hello
  password: <%= ENV['HELLO_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: hello_staging
  username: hello
  password: <%= ENV['HELLO_DATABASE_PASSWORD'] %>
